// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/leonf08/gophermart.git/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Orders is an autogenerated mock type for the Orders type
type Orders struct {
	mock.Mock
}

// CreateNewOrder provides a mock function with given fields: ctx, userID, orderNum
func (_m *Orders) CreateNewOrder(ctx context.Context, userID int64, orderNum string) error {
	ret := _m.Called(ctx, userID, orderNum)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, orderNum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrdersForUser provides a mock function with given fields: ctx, userID
func (_m *Orders) GetOrdersForUser(ctx context.Context, userID int64) ([]*models.Order, error) {
	ret := _m.Called(ctx, userID)

	var r0 []*models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*models.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrders creates a new instance of Orders. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrders(t interface {
	mock.TestingT
	Cleanup(func())
}) *Orders {
	mock := &Orders{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
